### ISSUE TITLE
Error when character spawns in repeats every tic

### ISSUE THREAD

**Issue by LuxPoseidon** [JoelOliMclean/NoRainDamage#3]
Hello! This mod has not been updated in a bit however in the case you are still available and willing to fix issues I will inform you of a current one here due to the recent Ashlands Update.

```
[Error  : Unity Log] MissingMethodException: Method not found: bool .EnvMan.IsWet()
Stack trace:
(wrapper dynamic-method) WearNTear.DMD<WearNTear::UpdateWear>(WearNTear,single)
WearNTearUpdater.Update () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
```

This occurs when spawning in for me. So startup errors just this when my character is in game.

**Comment by JoelOliMclean** [comment]
> Hello! This mod has not been updated in a bit however in the case you are still available and willing to fix issues I will inform you of a current one here due to the recent Ashlands Update.
> 
> ```
> [Error  : Unity Log] MissingMethodException: Method not found: bool .EnvMan.IsWet()
> Stack trace:
> (wrapper dynamic-method) WearNTear.DMD<WearNTear::UpdateWear>(WearNTear,single)
> WearNTearUpdater.Update () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
> ```
> 
> This occurs when spawning in for me. So startup errors just this when my character is in game.

Hey, I'm going to have a look, I've been away from Valheim modding for a while but I'll check it out. Thanks for raising! 🙌🏻

**Comment by JoelOliMclean** [comment]
> Hello! This mod has not been updated in a bit however in the case you are still available and willing to fix issues I will inform you of a current one here due to the recent Ashlands Update.
> 
> ```
> [Error  : Unity Log] MissingMethodException: Method not found: bool .EnvMan.IsWet()
> Stack trace:
> (wrapper dynamic-method) WearNTear.DMD<WearNTear::UpdateWear>(WearNTear,single)
> WearNTearUpdater.Update () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
> ```
> 
> This occurs when spawning in for me. So startup errors just this when my character is in game.

This has now been fixed! Version 1.2.2 available on nexus 👍🏻

**Comment by LuxPoseidon** [comment]
Can you update it on https://thunderstore.io/c/valheim/p/JoelOliMclean/NoRainDamage/ by chance?

**Comment by JoelOliMclean** [comment]
> Can you update it on https://thunderstore.io/c/valheim/p/JoelOliMclean/NoRainDamage/ by chance?

Done! Thanks for the reminder 🙌🏻  https://thunderstore.io/c/valheim/p/JoelOliMclean/NoRainDamage/
