### ISSUE TITLE
Experiencing the following error with the Bogwitch update

### ISSUE THREAD

**Issue by ddjammin** [JoelOliMclean/NoRainDamage#4]
[Error  : Unity Log] TargetParameterCountException: Number of parameters specified does not match the expected number.
Stack trace:
System.Reflection.RuntimeMethodInfo.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParameterInfo[] pinfo, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) (at <31687ccd371e4dc6b0c23a1317cf9474>:0)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <31687ccd371e4dc6b0c23a1317cf9474>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <31687ccd371e4dc6b0c23a1317cf9474>:0)
NoRainDamage.NoRainDamage.WearNTear_UpdateWear (WearNTear& __instance) (at <dc663a66b26d41a893770949e6a60e94>:0)
(wrapper dynamic-method) WearNTear.DMD<WearNTear::UpdateWear>(WearNTear,single)
WearNTearUpdater.UpdateWearNTear (System.Single deltaTime, System.Single time) (at <5f915391253541d3b835b2a5ff37908f>:0)
WearNTearUpdater.Update () (at <5f915391253541d3b835b2a5ff37908f>:0)

**Comment by JoelOliMclean** [comment]
Hey @ddjammin , thanks for bringing this to my attention, I'll look into it this week 🙏🏻

**Comment by JoelOliMclean** [comment]
Hopefully should have been fixed by latest update 🙏🏻 **v1.2.3** Let me know otherwise

**Comment by Leong-Qi-Jin** [comment]
Can confirm that this is fixed.
